### ISSUE TITLE
p132のコード　shapeの勘違い

### ISSUE THREAD

**Issue by akch-kk** [icoxfog417/baby-steps-of-rl-ja#14]
### 指摘事項
p132、code4-17で
```
# Convert the feature shape (f, w, h) => (w, h, f).
        feature = np.transpose(feature, (1, 2, 0))
```
となっているが，np.transpose前のfeature shapeは(f, h, w)であるので正しくは
```
# Convert the feature shape (f, h, w) => (h, w, f).
        feature = np.transpose(feature, (1, 2, 0))
```
だと思う。
### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [x] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p132

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます。channel x row x columnの感覚で書いていましたが、width x height表記だとrowがheightになりますね。その場合、ご指摘の通り`f, h, w`が正となります。
