### ISSUE TITLE
4.4 Policy Gradientでのパラメータ更新について

### ISSUE THREAD

**Issue by slaypni** [icoxfog417/baby-steps-of-rl-ja#15]
### 指摘事項

4.4のPolicy gradientの説明文およびサンプルコードについて、正しいか疑問に思う点があったので質問させていただけないでしょうか？
当該箇所のサンプルコードでは、毎ステップでreplay bufferを使って過去に得られた全てのエピソードからデータ `(state, action, weight)` をサンプルして学習を行っていると思います。
しかしながら、Policy gradientにおいては、学習に使って良いデータは現在のポリシーで得られたデータに限るべきなのではないでしょうか？ (replay bufferは使わず、更新は一度だけ)
というのも、ここでの `∇J(θ)` は現在のポリシーから得られた場合でなくては正しい意味を持たないからです。

[OpenAIのサイト](https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html)の最初の `You Should Know` とこの書籍の説明とで食い違いがあると思い、疑問に思ったのでissueをあげさせていただきました。

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [x] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

**Comment by icoxfog417** [comment]
お問い合わせありがとうございます。「ここでの `∇J(θ)` は現在のポリシーから得られた場合でなくては正しい意味を持たないからです。」という点について、もう少し説明を頂いてもよろしいでしょうか。

式からすると、 `∇J(θ)` にはd(s)=状態遷移の確率がありますが、Replay Bufferにしてしまうと確かにここが評価対象の戦略の状態遷移分布と合わなくなる気がします。行動確率は現在の戦略に従い計算されますが、その行動を取る状態への遷移がReplay Bufferからランダムに取られるため、遷移確率 X 行動確率 X 価値という期待値の原則が満たされなくなるということですね。

![image](https://user-images.githubusercontent.com/544269/54097796-0ddac380-43f5-11e9-9adb-464e3a28642c.png)

ご指摘の点は、↑の理解で合っているでしょうか？

**Comment by slaypni** [comment]
お返事ありがとうございます。

おっしゃるとおり、 `d(s)` がポリシーによって異なってくるので、replay bufferを使ってしまうと期待値のサンプリングとはみなせなくなってしまうのではないかな？と思います。
また、ポリシーが変わるとリターン `Q` のほうも値が異なってくるのではないでしょうか？(すなわち過去のリターンを使い回せない)

余談ですが、[こちらの記事](https://lilianweng.github.io/lil-log/2018/04/08/policy-gradient-algorithms.html)では、`Off-Policy Policy Gradient` という手法が紹介されており、そのような工夫をすればreplay bufferを使うことができるかもしれません。

**Comment by icoxfog417** [comment]
ご確認ありがとうございました。理解できました。

Replay Bufferを使う際は、[Off-Policy Policy Gradient](https://lilianweng.github.io/lil-log/2018/04/08/policy-gradient-algorithms.html#off-policy-policy-gradient)/[ACER](https://lilianweng.github.io/lil-log/2018/04/08/policy-gradient-algorithms.html#acer)のように重みをつけるようですね。stateは基準戦略(β)でサンプリングされるので、それに比しての重みをかけて調整するという感じですね。過去のQを使い回すべきでないのもご指摘の通りです。

この点は私自身気づかなかったので、修正する際は記載を完全に洗い替えせず、勘違いしうる点として記載をしようと思います。

問題は修正の方法ですが、以下つを考えています。よろしければご意見をお聞かせください。

1. 一度updateしたらReplay Bufferは空にし、更新後またためて埋まったら更新する
   * Pros: Buffer内が単一戦略のログになるため、既存の問題が解決する。コードの修正が少ない(クリアを入れれば良い)。
   * Cons: A2Cをシングルプロセスで行っているような実装になるため、実行時間がかさむ可能性がある。
2. 標準のA2Cの実装にしてしまう
   * Pros: 分散プレイを組み込んだA2Cベースの実装にすることで、既存の問題は解消する
   * Cons: 既存の実装と構成が大きく変わる
3. Weightを導入する
   * Pros: βが一様分布と仮定し、πに対する重み(importance weight)を導入する。Replay Bufferを使う場合はこうする必要がある、という解説にもつながる。
   * Cons: 標準のPolicy Gradientの解説からちょっと離れてしまう。

**Comment by slaypni** [comment]
指摘が的外れでなくてよかったです。

あくまで自分の考えですが、少なくとも4.4ではシンプルなPolicy Gradientの説明がされているのが良いのではないでしょうか。
そのため修正の方法としては1番目の方法が良いのではないでしょうか？(時間がかさむのも、それはそれで手法の特性を説明するものとしては良いのでは)
そのうえで可能であれば、2番目や3番目の紹介があるなどして、時間がかさむ問題やreplay bufferの問題についての解決法が紹介されていれば、なお良いのではないかと思います。

**Comment by icoxfog417** [comment]
お忙しいところコメントを頂きありがとうございます！

やはり、普通のPolicy Gradientの説明をきっちり行ったほうが良いですよね。まずは1で修正してみて、学習が行われるかを確認してみたいと思います。

**Comment by muupan** [comment]
ひょっとしたら @icoxfog417 さんに誤解があるかもしれないと思ったので補足させてもらうと、replay buffer内のstateの分布がd^{\pi_\theta}(s)に従ってないことについてはそのとおりなんですが、そこよりもむしろreplay buffer内の**action**の分布が\pi_\theta(a|s)に従ってないことのほうが問題です。古い\thetaを使ってactionを選んだ際のデータを直接は使えないだけでなく、例えばepsilon greedyを使ってしまうとそれについても\pi_\theta(a|s)からのサンプルでなくなるため補正が必要です。

**Comment by icoxfog417** [comment]
コメントを頂きありがとうございます！

π_θ(a|s)の確率値自体は最新のモデルから計算していますが、確率値の計算対象となるaはご指摘の通り過去の戦略で選ばれたものなので、確かにこの点も問題ですね。

やはり、Policy Gradientにおいては更新対象の戦略以外でサンプルされたデータは使うことができない、ということですね(重みで調整しない限り)。

**Comment by icoxfog417** [comment]
こちらの内容を記事に書き起こしました。
https://medium.com/programming-soda/replay-buffer%E3%81%8Cpolicy-gradient%E3%81%A7%E4%BD%BF%E3%81%88%E3%81%AA%E3%81%84%E7%90%86%E7%94%B1-57801f439aa6
