### ISSUE TITLE
A2Cの勾配計算について

### ISSUE THREAD

**Issue by muupan** [icoxfog417/baby-steps-of-rl-ja#16]
https://github.com/icoxfog417/baby-steps-of-rl-ja/blob/master/FN/a2c_agent.py#L71-L74

このA2Cのlossを計算している箇所ですが、`policy_loss`を最小化するための勾配（i.e. policyを改善するための勾配）が`advantages`を通じてvalue functionにまで流れているように見えます。softplusを挟まないとadvantageがおかしな値になることを https://medium.com/programming-soda/%E5%BC%B7%E5%8C%96%E5%AD%A6%E7%BF%92%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8Badvantage%E3%81%AE%E6%94%B9%E5%96%84-9cc0167d9eb2 で報告されてましたが、これが原因ではないかと推測します。

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます！

`policy_loss` => `advantages` => `values` => `critic_layer`という流れで影響が出ている、という理解で良いでしょうか？

これを回避するには、advantages自体かvaluesを外側で計算しておいて、`tf.placeholder`で渡して使う形になるでしょうか(参考: [openai/baselines/a2c.py](https://github.com/openai/baselines/blob/master/baselines/a2c/a2c.py#L91))。

**Comment by icoxfog417** [comment]
@muupan `tf.stop_gradient` で対応できました！ありがとうございます。

https://github.com/icoxfog417/baby-steps-of-rl-ja/blob/96fb3e2b906ffa972ec983bd8d1ed76d8fb9852d/FN/a2c_agent.py#L74
