### ISSUE TITLE
p.20 「報酬の総和」の式の誤植

### ISSUE THREAD

**Issue by ryamauchi** [icoxfog417/baby-steps-of-rl-ja#28]
### 指摘事項
すでに指摘されているかもしれませんが一応。

![image](https://user-images.githubusercontent.com/19339415/58141834-af955100-7c7f-11e9-9008-e82398936b97.png)

となっていますが、

![image](https://user-images.githubusercontent.com/19339415/58141873-d94e7800-7c7f-11e9-9782-a067d403a9ee.png)

の間違いだと思います。
あるいは

![image](https://user-images.githubusercontent.com/19339415/58141912-0b5fda00-7c80-11e9-9460-b85fb4642792.png)

### 指摘箇所

* [x] Day1: 強化学習の位置づけを知る
* [x] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p.20, p.32

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
ご確認ありがとうございます！以下で修正する予定です。

![image](https://user-images.githubusercontent.com/544269/59167685-77da4480-8b6d-11e9-8918-b23029f4ba98.png)
