### ISSUE TITLE
DP/bellman_equation.py の実行結果が違う

### ISSUE THREAD

**Issue by yujirokatagiri** [icoxfog417/baby-steps-of-rl-ja#31]
### 指摘事項

p.37 の code2-4 は DP/bellman_equation.py の実行結果だと思いますが, 私の実行結果は以下のようになり, code2-4 と異なりました。

```
$ python DP/bellman_equation.py 
0.7880942034605892
0.9068026334400001
-0.96059601
```

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [x] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p.37

### 実行環境

* OS: mac
* Python version: 
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます。修正済みです！
