### ISSUE TITLE
Day3.3 p75の単語誤植

### ISSUE THREAD

**Issue by wisteria2gp** [icoxfog417/baby-steps-of-rl-ja#33]
### 指摘事項
第3刷 Day3.3 p75、本文上から5,7行目それぞれで「Off-poicy」,「On-poicy」となっておりpo __l__ icyのL抜けではないでしょうか。

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [x] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p75

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
修正しました！
