### ISSUE TITLE
p.137 誤植

### ISSUE THREAD

**Issue by sonodano** [icoxfog417/baby-steps-of-rl-ja#36]
### 指摘事項
p.137一行目 Experience Reply → Experience Replay

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ x ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p. 137

### 実行環境
第一版です

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます！"Reply"になっているところが複数あったのでまとめて修正します。

**Comment by icoxfog417** [comment]
改訂2版 3版での修正点

* p153: Reply => Replay
