### ISSUE TITLE
Day1 p20 割引現在価値 誤植

### ISSUE THREAD

**Issue by BrambleXu** [icoxfog417/baby-steps-of-rl-ja#40]
### 指摘事項

”割引現在価値”は未来値を計算しているから、英語はDiscounted Future Rewardだと考えています。そうすると、日本語の翻訳は”割引未来報酬”だと思います。

### 指摘箇所

* [x] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p20

**Comment by icoxfog417** [comment]
日本語的には割引現在価値で合っているはず(用例的に)。ただ、明確な対訳がみつからんのでちょっと調べる。

**Comment by BrambleXu** [comment]
問題はなかったです。
英語はnet present value
