### ISSUE TITLE
Kindle版 4.1.3 code 4-8 にてアンダースコア "_" が消えてるように見える

### ISSUE THREAD

**Issue by arkB** [icoxfog417/baby-steps-of-rl-ja#42]
### 指摘事項
![キャプチャ](https://user-images.githubusercontent.com/7195976/70017969-ffa68600-15c7-11ea-84b3-c5b7986d51e5.PNG)

Kindle版で 4.1.3 code 4-8 Trainerクラス の trainer_name内の下記部分のアンダースコア "_" が消えてるように見えます（添付画像参照）。

```
class_name = self.  class  .  name  → class_name = self.__class__.__name__
```

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [x] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p
Kindle版 No.1430/3649

### 実行環境

* OS: Windows PC より Kindle アプリから確認
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
ご報告ありがとうございます！こちら確認してみます。

**Comment by icoxfog417** [comment]
校正段階の誤植であると確認が取れました(現行での誤りはありません)。
以下の箇所で欠落があります。

* code: 4-7		self.__class__.__name__
* code: 4-9		dirname(__file__)
* 133ページ下から4行目の本文中		__init__
* code: 6-13		dirname(__file__)

次回重版時に訂正されるとのことです。ご指摘ありがとうございました。

**Comment by icoxfog417** [comment]
改訂2版 2版で修正されていることを確認しました、

code: 4-7
![image](https://user-images.githubusercontent.com/544269/118353903-6b559680-b5a3-11eb-959f-b9b688294b9d.png)

code: 4-10 (4-9でなく4-10)
![image](https://user-images.githubusercontent.com/544269/118353954-993adb00-b5a3-11eb-8b20-56379b42a00a.png)

p145 (p133でなく。他のinitの箇所も確認済み)
![image](https://user-images.githubusercontent.com/544269/118354035-11090580-b5a4-11eb-8cda-1e3625501762.png)

code: 6-13 dirname(file)
![image](https://user-images.githubusercontent.com/544269/118354076-3f86e080-b5a4-11eb-91f0-6455e26bfb72.png)
