### ISSUE TITLE
p65 「状態価値」誤植

### ISSUE THREAD

**Issue by mnishiki** [icoxfog417/baby-steps-of-rl-ja#45]
### 指摘事項
P.65の１行目にて  
「show_q_valueはエージェントの**状態価値**を可視化するための関数です」とありますが、正しくは
「show_q_valueはエージェントの**状態評価**を可視化するための関数です」
ではないでしょうか？

（背景）
「状態価値」という単語は本書ではp65で初めて登場した単語で、
次の行を読むと「エージェントは各状態における各行動の**評価**をQという変数に記録します」とあるので、「状態価値」ではなく「状態評価」が正しいのかと推測しました。
（「状態価値」の意味が分かっていないのですが、定義は本書のどこかでされているのでしょうか？）

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [x] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p65（第１刷）

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
変数Qに格納に格納されているのは、正確には「ある状態sにおいて行動aをとる価値」であるため「行動価値」が正です(最新版では修正されています)。

状態価値は、状態sが(報酬の獲得に)どれだけ近い状態であるかを表します。評価/価値は同等の意味で、用語の違いになります(英語では"value"とされることが多いため、後の版では値は「価値」、値を算出する行為を「評価」にしています)。
