### ISSUE TITLE
p.60 誤字脱字

### ISSUE THREAD

**Issue by Ganariya** [icoxfog417/baby-steps-of-rl-ja#48]
### 指摘事項

改訂版のp.60にて
「これがTD法でです。」
となっています。

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ へ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p60

**Comment by icoxfog417** [comment]
改訂2版の段階で修正されていることを確認しました。

![image](https://user-images.githubusercontent.com/544269/118354205-e4a1b900-b5a4-11eb-9318-6083c310b3f2.png)
