### ISSUE TITLE
ソースコードによって名前がついていない

### ISSUE THREAD

**Issue by Ganariya** [icoxfog417/baby-steps-of-rl-ja#49]
### 指摘事項

本の中で
code3-7のようにコードが出てきますが
ソースコード名がついていないときがあるため、ソースコード名がついていると嬉しいです。

また、それぞれのファイルでどういう由来でそういうディレクトリになっているか本で少しでも記載があると覚えやすいです。
ELの略が分かりませんでした。（EpsilonとLakeでしょうか）

**Comment by icoxfog417** [comment]
改訂2版 2版ですべてのコードに番号がついていることを確認しました。
