### ISSUE TITLE
モンテカルロ法での学習率について

### ISSUE THREAD

**Issue by lucidfrontier45** [icoxfog417/baby-steps-of-rl-ja#50]
### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [x] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

Kindle版 Day3 code3-7の学習率alphaは
```py
alpha = 1 / N[s][a]
```
となっています。これは最終的には(state, action) = (s, a)となるケースのQ値の平均をとることになると理解していいでしょうか？
また、TD法と同様に定数をセットしてもいいのでしょうか？一応定数でも学習できてはいるようです。

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
はい、ご指摘の通りQ値の平均をとることになります。
alphaは実際の報酬を組み込む割合で、定率でも学習結果は反映されるため、学習は可能です。

![image](https://user-images.githubusercontent.com/544269/118354541-76f68c80-b5a6-11eb-8800-346b435b17c5.png)
