### ISSUE TITLE
p.60，61 モンテカルロ法更新式など 誤植 (改訂版第2版)

### ISSUE THREAD

**Issue by Zu-rin** [icoxfog417/baby-steps-of-rl-ja#55]
### 指摘事項
モンテカルロ法の更新式に誤植を見つけました．
- 修正前
![texclip20210203135701](https://user-images.githubusercontent.com/54212697/106700189-b3b9fb80-6627-11eb-8ef3-ae55d9549885.png)
- 修正後
![texclip20210203135806](https://user-images.githubusercontent.com/54212697/106700290-e06e1300-6627-11eb-8cd4-e1c6e5c1396b.png)

p.61のepisode end の式にも同様の誤植が存在します．

またepiside end の式最後の項のラムダの次数はT-t-1が正しいと思います．

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [x] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p.60，61

### 実行環境

* OS: 
* Python version:
* `pip freeze`の実行結果 (下に添付)

### エラー内容

(例外のメッセージ、ログ、画面ショットなどを添付)

**Comment by icoxfog417** [comment]
改訂2版 3版での修正

p60

* r_{T-t} => r_T
* エピソード終了(T-t) => エピソード終了(T)

![image](https://user-images.githubusercontent.com/544269/118355426-f1c1a680-b5aa-11eb-99a9-dc7a59d560aa.png)

p61

* episode end: γ^{T-t-1}


![image](https://user-images.githubusercontent.com/544269/118355605-d30fdf80-b5ab-11eb-94e4-a4a7f84b9c76.png)
