### ISSUE TITLE
p,64　状態の表現について

### ISSUE THREAD

**Issue by Masa0u0** [icoxfog417/baby-steps-of-rl-ja#57]
### 指摘事項
```
s = r * nrow + c
```
の部分に関して、正しくは
```
s = r * ncol + c
```
ではないでしょうか？
私が間違っているかもしれませんがご確認をお願いいたします。

### 指摘箇所

* [ ] Day1: 強化学習の位置づけを知る
* [x] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p64

**Comment by icoxfog417** [comment]
`s = r * ncol + c`が正しいです。ご指摘ありがとうございます！

![image](https://user-images.githubusercontent.com/544269/118355916-b2488980-b5ad-11eb-9ac0-5c42e4bba00e.png)
