### ISSUE TITLE
P28のコードの誤植

### ISSUE THREAD

**Issue by yshr10ic** [icoxfog417/baby-steps-of-rl-ja#9]
### 指摘事項
code1-6のmain関数の中で、ゲームを10回試行しているが、`while not done`以降のインデントが一段ずれている。

### 指摘箇所

* [x] Day1: 強化学習の位置づけを知る
* [ ] Day2: 強化学習の解法(1): 環境から計画を立てる
* [ ] Day3: 強化学習の解法(2): 経験から計画を立てる
* [ ] Day4: 強化学習に対するニューラルネットワークの適用
* [ ] Day5: 強化学習の弱点
* [ ] Day6: 強化学習の弱点を克服するための手法
* [ ] Day7: 強化学習の活用領域

ページ番号: p.28

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます。#3 にて対応済みです。
